# Site settings
title: An Inconsistent Universe
email: clarissa.littler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for my mathematical and personal ramblings. A possible replacement for my wordpress blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clarissalittler.github.io/" # the base hostname & protocol for your site
twitter_username: ClarissaAdjoint
github_username:  clarissalittler

# Build settings
markdown: kramdown
